[package]
name = "pidrs"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"] # This crate type is required for JNI

[dependencies]
jni = "0.21"

[profile.release]
opt-level = 3
