[env]
#OPENCV_LINK_LIBS = "opencv_world481"
# comment these out for local build
OPENCV_INCLUDE_PATHS = "C:/tools/opencv/build/include/opencv2"
OPENCV_LINK_PATHS = "D:/Documents/Programming/CenterStage/lib/opencv-build/lib/armeabi-v7a"
OPENCV_LINK_LIBS = "libopencv_world"
